def complement(x):
    if x == 'A':
        return 'T'
    elif x == 'T':
        return 'A'
    elif x == 'C':
        return 'G'
    elif x == 'G':
        return 'C'
    
DNA ='CGAATCGTTTTACAAAACTCTTATAAAGGCTACACTGAGTATATTCTACAGGTCAGCGACGGTTGCGTTAATCTCACTAATAACGTAACCGACTCGGAGAGGGCCACTAGTCATTTAATCCTCGGCATCATTTCCACTAAGACCAGACGCTCCGTTCATTAAGGCTAACTTTCCCGAGGTGGCAAGATAAGGTTGGCGGAAGGACGATACTCGACGACGGGCTGCCCATACACAAAGACTGCATCATCCCTCTGTCTCTGAAGAAATTTTCTAACTTGGAATCGATCGGTGATGAACATTCGAATATGTCTTGAACTACAAGCTTGCTAGGCGCGAGGAATTAATGGGTTATAATCTACTTGACCGCGAGGCAGGACAGCCCAGTTACTCGCATGGAGGTGCGCTGCACGGCAAAGAACAAACCCATGCAATCATTTTGTACACGTCTTCTCGAACCTCATGGCTTAGGGAATCCTGGTCACTCGTCACCCTTACCTCTTTATATCCGATGTCTTAAGCGGCCACTTTCAGTAAGCTCAAGCGACGAGCCTGGATCAGCTCAAACGGGACGGGGGGCACAAGTTCAATGGATACTCGGCCACCGCTCATAGCGGGAAAGAGTATCACTAGTGAACTCAAGCGCGTAAGGGCCGGTAGATGATGCGCTCAAATGATTACACGTGCCTTACACAGTCCATCTGGGCCTTCCTGTTGTGCAACGCTACCGTAAAGGGTGGGGTTAACGCGATCTCGTATTACGATCTATCACAATTAGTAGCCGGGAAAACCTAGTACACAATCCGACGCGCAATAGCTTAAGCTTACCATGCTTACATACAA'

reversed = DNA[::-1]
revDNA = ''
for base in reversed:
        revDNA += complement(base)

print(revDNA)



