# had to cheat a little with the X's in the end, because I would get an error message regarding the index being out of range
s = "TGTTTGTCCGGAGCTATTTGTCCCTTTGTCCTTTGTCCTTTGTCCGTTCGGCCTTTGTCCCGGTATTTTGTCCATGGTTTTGTCCGCCTATTTTGTCCCCAATTTGTCCAATTTTGTCCGCAATTTGTCCGATTTGTCCTTTGTCCCATTTGTCCGGGGTTTGTCCTTTGTCCGGGGTTTGTCCTTTGTCCAGATTTGTCCACAGTTTGTCCTTTGTCCGTTTGTCCCAATTTTGTCCATGTTTTTTGTCCTATTTGTCCTGTGCGTTTGTCCAGAATTTTGTCCCTTTGTCCAGGATTTTGTCCATTTGTCCGCTTTGTCCAAGTGCCCATATGTTTGTCCCCTTTGTCCTTTGTCCGATTTGTCCACTTCGGAAAGCAATTTGTCCGGCGTGGGTGAGTTTGTCCTTTGTCCATTGATCACTTTTGTCCTTTGTCCTTTTGTCCCTCTTTTGTCCTTTTGTCCGCTTTGTCCCGATGCTGCTATTTGTCCCTTCGTTTGCTCTTTGTCCCGGTTTGTCCAACTTTGTCCTACCTTTGTCCCTTTGTCCATTTTTGTCCTTTTGTCCCAGAGGACGTTTGTCCGCAGCTTTGTCCACCATTTGTCCCTTTGTCCTTTGTCCCCGGGGCCAACGCTTTGTCCCGATTTGTCCCATTTGTCCTAGTTGGTTTGTCCGTTTGTCCTTTGTCCGTCATTTGTCCAGAGCTTTGTCCCAGGGACAAGTTTGTCCCTGGTTTTGTCCATTTGTCCATATCTTTGTCCCTGGCCAGTTTGTCCGTTTGTCCCGTTTGTCCATTTGTCCCATTTGTCCGGTTTGTCCTCGTTTTTTGTCCTTTTGTCCTTTGTCCTTTTGTCCCCGTTTGTCCTTTGTCCTTTGTCCACAGAAATGACGTTTGTCCTTTGTCCTTTTGTCCCCTTTTGTCCXXXXXXXXXXX"
t = "TTTGTCCTT"
positions = []

for pos_s, base_s in enumerate(s):
    for pos_t, base_t in enumerate(t):
        if s[pos_s + pos_t] != t[pos_t]:
            break
        if (pos_t + 1) == len(t):
            positions.append(pos_s + 1)
# this for loop is only for the rosalind formating
for a in positions:
    print(a, end=" ")
print()